export const PHONE_COUNTRY_CODES: { code: string; label: string }[] = [
  { code: "+212", label: "Maroc (+212)" },
  { code: "+213", label: "Algérie (+213)" },
  { code: "+216", label: "Tunisie (+216)" },
  { code: "+20", label: "Égypte (+20)" },
  { code: "+33", label: "France (+33)" },
  { code: "+34", label: "Espagne (+34)" },
  { code: "+49", label: "Allemagne (+49)" },
  { code: "+39", label: "Italie (+39)" },
  { code: "+351", label: "Portugal (+351)" },
  { code: "+44", label: "Royaume-Uni (+44)" },
  { code: "+1", label: "États-Unis / Canada (+1)" },
  { code: "+32", label: "Belgique (+32)" },
  { code: "+31", label: "Pays-Bas (+31)" },
  { code: "+41", label: "Suisse (+41)" },
  { code: "+7", label: "Russie (+7)" },
  { code: "+86", label: "Chine (+86)" },
  { code: "+82", label: "Corée du Sud (+82)" },
  { code: "+90", label: "Turquie (+90)" },
  { code: "+972", label: "Israël (+972)" },
  { code: "+966", label: "Arabie Saoudite (+966)" },
  { code: "+971", label: "Émirats Arabes Unis (+971)" },
  { code: "+974", label: "Qatar (+974)" },
];
